spring:
  datasource:
    url: jdbc:postgresql://192.168.14.109:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: tmax1234
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    generate-ddl: false
#  liquibase:
#    change-log: classpath:/db/changelog-master.xml